//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGYKIEN
    {
        public BANGYKIEN()
        {
            this.CTBQYKIENs = new HashSet<CTBQYKIEN>();
        }
    
        public int MAYK { get; set; }
        public string MADH { get; set; }
        public string NOIDUNG { get; set; }
        public int SLDONGY { get; set; }
        public long NCPDONGY { get; set; }
        public int SLKHONGDONGY { get; set; }
        public long NCPKHONGDONGY { get; set; }
        public int SLYKKHAC { get; set; }
        public long NCPKHAC { get; set; }
        public int SOPHIEUPHATRA { get; set; }
        public long TUONGDUONGCOPHIEU { get; set; }
    
        public virtual DHCD DHCD { get; set; }
        public virtual ICollection<CTBQYKIEN> CTBQYKIENs { get; set; }
    }
}
