//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGBAUHDQT
    {
        public BANGBAUHDQT()
        {
            this.CT_BAUHDQT = new HashSet<CT_BAUHDQT>();
        }
    
        public string MADH { get; set; }
        public int MACD { get; set; }
        public string HINHTHUCBAU { get; set; }
        public Nullable<int> SLPHIEUBAU { get; set; }
    
        public virtual CT_DHCD CT_DHCD { get; set; }
        public virtual ICollection<CT_BAUHDQT> CT_BAUHDQT { get; set; }
    }
}
