//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODONG
    {
        public CODONG()
        {
            this.CT_DHCD = new HashSet<CT_DHCD>();
            this.USERCDs = new HashSet<USERCD>();
        }
    
        public int MACD { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> CMND { get; set; }
        public string NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string DiaChi { get; set; }
        public string QuocTich { get; set; }
        public string ChucVu { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public string TrinhDoChuyenMon { get; set; }
        public string ANHCD { get; set; }
    
        public virtual ICollection<CT_DHCD> CT_DHCD { get; set; }
        public virtual ICollection<USERCD> USERCDs { get; set; }
    }
}
