//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITDHCD
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATECOMMIT { get; set; }
        public string MADH { get; set; }
    
        public virtual DHCD DHCD { get; set; }
    }
}
