//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAUHDQT
    {
        public int MACT { get; set; }
        public string MAHDQT { get; set; }
        public string MANGUOIBAU { get; set; }
        public Nullable<int> SLPHIEUBAU { get; set; }
        public string HINHTHUCBAU { get; set; }
        public Nullable<System.DateTime> THOIGIANBAU { get; set; }
        public bool LAHOPLE { get; set; }
    
        public virtual THANHVIENHDQT THANHVIENHDQT { get; set; }
        public virtual CT_DHCD CT_DHCD { get; set; }
    }
}
