//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DHCD
    {
        public DHCD()
        {
            this.BANGYKIENs = new HashSet<BANGYKIEN>();
            this.THANHVIENBKS = new HashSet<THANHVIENBK>();
            this.THANHVIENHDQTs = new HashSet<THANHVIENHDQT>();
            this.CT_DHCD = new HashSet<CT_DHCD>();
        }
    
        public string MADH { get; set; }
        public string TenDH { get; set; }
        public Nullable<int> YEARDHCD { get; set; }
        public Nullable<int> STTDHTRONGNAM { get; set; }
        public Nullable<int> nQKin { get; set; }
        public Nullable<int> nQBefore { get; set; }
        public Nullable<int> nDeCuHDQT { get; set; }
        public Nullable<int> nUngCuHDQT { get; set; }
        public Nullable<int> nDeCuBKS { get; set; }
        public Nullable<int> nUngCuBKS { get; set; }
        public Nullable<int> nBauBoSungHDQT { get; set; }
        public Nullable<int> nBauBOSungBKS { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public Nullable<int> TONGSOPHIEU { get; set; }
    
        public virtual ICollection<BANGYKIEN> BANGYKIENs { get; set; }
        public virtual ICollection<THANHVIENBK> THANHVIENBKS { get; set; }
        public virtual ICollection<THANHVIENHDQT> THANHVIENHDQTs { get; set; }
        public virtual ICollection<CT_DHCD> CT_DHCD { get; set; }
    }
}
