//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCEPTIONAPP
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public System.DateTime ERRORDATE { get; set; }
        public string ERRORUSER { get; set; }
    }
}
