//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDHCDEntities : DbContext
    {
        public QLDHCDEntities()
            : base("name=QLDHCDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGBAUBK> BANGBAUBKS { get; set; }
        public virtual DbSet<BANGBAUHDQT> BANGBAUHDQTs { get; set; }
        public virtual DbSet<BANGYKIEN> BANGYKIENs { get; set; }
        public virtual DbSet<CODONG> CODONGs { get; set; }
        public virtual DbSet<CT_BAUBKS> CT_BAUBKS { get; set; }
        public virtual DbSet<CT_BAUHDQT> CT_BAUHDQT { get; set; }
        public virtual DbSet<CTBQYKIEN> CTBQYKIENs { get; set; }
        public virtual DbSet<DHCDSTT> DHCDSTTs { get; set; }
        public virtual DbSet<EXCEPTIONAPP> EXCEPTIONAPPs { get; set; }
        public virtual DbSet<THANHVIENBK> THANHVIENBKS { get; set; }
        public virtual DbSet<THANHVIENHDQT> THANHVIENHDQTs { get; set; }
        public virtual DbSet<USERCD> USERCDs { get; set; }
        public virtual DbSet<UYQUYEN> UYQUYENs { get; set; }
        public virtual DbSet<DHCD> DHCDs { get; set; }
        public virtual DbSet<CT_DHCD> CT_DHCD { get; set; }
    }
}
