//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIENBK
    {
        public string MATD { get; set; }
        public string HINHTHUCBAU { get; set; }
        public Nullable<int> SLPHIEUBAU { get; set; }
        public Nullable<bool> LADECU { get; set; }
        public Nullable<bool> LAUNGCU { get; set; }
        public Nullable<bool> LATHAYTHE { get; set; }
        public Nullable<bool> LACHUTICH { get; set; }
        public Nullable<bool> LASUCCESS { get; set; }
    
        public virtual CT_DHCD CT_DHCD { get; set; }
    }
}
