//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIENHDQT
    {
        public THANHVIENHDQT()
        {
            this.CT_BAUHDQT = new HashSet<CT_BAUHDQT>();
        }
    
        public string MATD { get; set; }
        public string HINHTHUCBAU { get; set; }
        public Nullable<long> SLPHIEUBAU { get; set; }
        public string THANHVIENTYPE { get; set; }
        public bool LACHUTICH { get; set; }
        public bool LASUCCESS { get; set; }
    
        public virtual ICollection<CT_BAUHDQT> CT_BAUHDQT { get; set; }
        public virtual CT_DHCD CT_DHCD { get; set; }
    }
}
