//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIENBK
    {
        public string MADH { get; set; }
        public int MACD { get; set; }
        public Nullable<int> SOPHIEUBAU { get; set; }
        public Nullable<int> LATHAYTHE { get; set; }
    
        public virtual CODONG CODONG { get; set; }
        public virtual DHCD DHCD { get; set; }
    }
}
