//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDHCDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYQUYEN
    {
        public int MAUQ { get; set; }
        public string MADH { get; set; }
        public int MANGCHUYEN { get; set; }
        public int MANGNHAN { get; set; }
        public Nullable<int> SLUQ { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    
        public virtual CT_DHCD NGUOICHUYEN { get; set; }
        public virtual CT_DHCD NGUOINHAN { get; set; }
    }
}
